notifications:
  email: false

# Quick boot options
sudo: false
cache:
  directories:
    - node_modules

# Ignore version tags
branches:
  except:
    - /^v[0-9]/

# Language options
language: node_js
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
node_js:
  - 4
before_script:
  - npm prune
script:
  - npm test
  - npm run lint

# Npm publish options
deploy:
  skip_cleanup: true # keep the devDependencies
  provider: npm
  email: i59naga@icloud.com
  api_key:
    secure: DACYlgorgqDtpoR0JjuVpqM/dENX7eUI5vyFIKMqyAmtKAG9rzsFhe/+DD5qJoUWjroZxWIEjS83MDYez+syqumi8oVvDbbQ8Edx7mFQ9F5E/zifWWcRjnw8hGKgp3/1CRFPT/H3ekDvJEu036YdrZyCYw0BvNi6pYMzSRx9y2ZlMMHP2rL0bfzF9Zl/UGRTXvkeam2W19XZhtqQ/k79qnLSpSYCzEeaUpP93FTEehEleD6dAVQq5adEVY5DrtRAM0UK9sAOSxgOHK4CgEFzGEHESa3WBMENd3rjjvkwDc1g5zvebWKV1VcZJBgPAX55rs50Fjn9RBc9tmN4DNGdHKzCoEFQftTZ716Cug0/pSW7T115yP4YWOhM3MBnW8t6Ic1csorZKhY+YPu6BIh2hN3z+V3pZiV3oOoq6UzahIGrfyZPpBrq/ofU92aBNRLn9ZBmcjbPS6g7r4HKlgDlzhszMZZj2wdRXPbsCOPko8moYn97KBX/tb/qBWAAZhU8D67bgdgDR2SDl0Bdz3QFYvsqf/286gSHrZPLf+bGuBeY6hRCPKQjUZat6+plD95VmkB0bs+NWQhtw6VOAFqiq1pfjm3JZxbn7W2ubBzcRNBdJpfHancXdbbPHNwHi0sqeoLYHV0zqVuJ9X460/RDrNFc2jRTNdVxnvYRfxdZxb8=
  on:
    node: 4
    all_branches: true
